<?php
/**
 * BankTransferStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tatrapayplus\TatrapayplusApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TatraPayPlus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1_2024-05-27v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tatrapayplus\TatrapayplusApiClient\Model;
use \Tatrapayplus\TatrapayplusApiClient\ObjectSerializer;

/**
 * BankTransferStatus Class Doc Comment
 *
 * @category Class
 * @description The transaction status is filled with codes of the ISO 20022
 * @package  Tatrapayplus\TatrapayplusApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BankTransferStatus
{
    /**
     * Possible values of this enum
     */
    public const ACCC = 'ACCC';

    public const ACCP = 'ACCP';

    public const ACSC = 'ACSC';

    public const ACSP = 'ACSP';

    public const ACTC = 'ACTC';

    public const ACWC = 'ACWC';

    public const ACWP = 'ACWP';

    public const RCVD = 'RCVD';

    public const PDNG = 'PDNG';

    public const RJCT = 'RJCT';

    public const CANC = 'CANC';

    public const ACFC = 'ACFC';

    public const PATC = 'PATC';

    public const PART = 'PART';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACCC,
            self::ACCP,
            self::ACSC,
            self::ACSP,
            self::ACTC,
            self::ACWC,
            self::ACWP,
            self::RCVD,
            self::PDNG,
            self::RJCT,
            self::CANC,
            self::ACFC,
            self::PATC,
            self::PART
        ];
    }
}


