<?php
/**
 * CardDetail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tatrapayplus\TatrapayplusApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TatraPayPlus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1_2024-05-27v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tatrapayplus\TatrapayplusApiClient\Model;

use \ArrayAccess;
use \Tatrapayplus\TatrapayplusApiClient\ObjectSerializer;

/**
 * CardDetail Class Doc Comment
 *
 * @category Class
 * @description Card pay information
 * @package  Tatrapayplus\TatrapayplusApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CardDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'cardDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'card_pay_lang_override' => 'string',
        'is_pre_authorization' => 'bool',
        'card_holder' => 'string',
        'billing_address' => '\Tatrapayplus\TatrapayplusApiClient\Model\Address',
        'shipping_address' => '\Tatrapayplus\TatrapayplusApiClient\Model\Address',
        'comfort_pay' => '\Tatrapayplus\TatrapayplusApiClient\Model\CardIdentifierOrRegister'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'card_pay_lang_override' => null,
        'is_pre_authorization' => null,
        'card_holder' => null,
        'billing_address' => null,
        'shipping_address' => null,
        'comfort_pay' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'card_pay_lang_override' => false,
        'is_pre_authorization' => false,
        'card_holder' => false,
        'billing_address' => false,
        'shipping_address' => false,
        'comfort_pay' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'card_pay_lang_override' => 'cardPayLangOverride',
        'is_pre_authorization' => 'isPreAuthorization',
        'card_holder' => 'cardHolder',
        'billing_address' => 'billingAddress',
        'shipping_address' => 'shippingAddress',
        'comfort_pay' => 'comfortPay'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'card_pay_lang_override' => 'setCardPayLangOverride',
        'is_pre_authorization' => 'setIsPreAuthorization',
        'card_holder' => 'setCardHolder',
        'billing_address' => 'setBillingAddress',
        'shipping_address' => 'setShippingAddress',
        'comfort_pay' => 'setComfortPay'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'card_pay_lang_override' => 'getCardPayLangOverride',
        'is_pre_authorization' => 'getIsPreAuthorization',
        'card_holder' => 'getCardHolder',
        'billing_address' => 'getBillingAddress',
        'shipping_address' => 'getShippingAddress',
        'comfort_pay' => 'getComfortPay'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CARD_PAY_LANG_OVERRIDE_SK = 'SK';
    public const CARD_PAY_LANG_OVERRIDE_EN = 'EN';
    public const CARD_PAY_LANG_OVERRIDE_DE = 'DE';
    public const CARD_PAY_LANG_OVERRIDE_HU = 'HU';
    public const CARD_PAY_LANG_OVERRIDE_CZ = 'CZ';
    public const CARD_PAY_LANG_OVERRIDE_ES = 'ES';
    public const CARD_PAY_LANG_OVERRIDE_FR = 'FR';
    public const CARD_PAY_LANG_OVERRIDE_IT = 'IT';
    public const CARD_PAY_LANG_OVERRIDE_PL = 'PL';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCardPayLangOverrideAllowableValues()
    {
        return [
            self::CARD_PAY_LANG_OVERRIDE_SK,
            self::CARD_PAY_LANG_OVERRIDE_EN,
            self::CARD_PAY_LANG_OVERRIDE_DE,
            self::CARD_PAY_LANG_OVERRIDE_HU,
            self::CARD_PAY_LANG_OVERRIDE_CZ,
            self::CARD_PAY_LANG_OVERRIDE_ES,
            self::CARD_PAY_LANG_OVERRIDE_FR,
            self::CARD_PAY_LANG_OVERRIDE_IT,
            self::CARD_PAY_LANG_OVERRIDE_PL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('card_pay_lang_override', $data ?? [], null);
        $this->setIfExists('is_pre_authorization', $data ?? [], null);
        $this->setIfExists('card_holder', $data ?? [], null);
        $this->setIfExists('billing_address', $data ?? [], null);
        $this->setIfExists('shipping_address', $data ?? [], null);
        $this->setIfExists('comfort_pay', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCardPayLangOverrideAllowableValues();
        if (!is_null($this->container['card_pay_lang_override']) && !in_array($this->container['card_pay_lang_override'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'card_pay_lang_override', must be one of '%s'",
                $this->container['card_pay_lang_override'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['card_holder'] === null) {
            $invalidProperties[] = "'card_holder' can't be null";
        }
        if ((mb_strlen($this->container['card_holder']) > 45)) {
            $invalidProperties[] = "invalid value for 'card_holder', the character length must be smaller than or equal to 45.";
        }

        if ((mb_strlen($this->container['card_holder']) < 2)) {
            $invalidProperties[] = "invalid value for 'card_holder', the character length must be bigger than or equal to 2.";
        }

        if (!preg_match("/^[ 0-9a-zA-Z.@_-]{2,45}$/", $this->container['card_holder'])) {
            $invalidProperties[] = "invalid value for 'card_holder', must be conform to the pattern /^[ 0-9a-zA-Z.@_-]{2,45}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets card_pay_lang_override
     *
     * @return string|null
     */
    public function getCardPayLangOverride()
    {
        return $this->container['card_pay_lang_override'];
    }

    /**
     * Sets card_pay_lang_override
     *
     * @param string|null $card_pay_lang_override It is possible to override the accept-language header for the CardPay payment method. This override only affects CardPay itself, not the whole TatraPayPlus service.  If it is empty , then accept-language is taken into account
     *
     * @return self
     */
    public function setCardPayLangOverride($card_pay_lang_override)
    {
        if (is_null($card_pay_lang_override)) {
            throw new \InvalidArgumentException('non-nullable card_pay_lang_override cannot be null');
        }
        $allowedValues = $this->getCardPayLangOverrideAllowableValues();
        if (!in_array($card_pay_lang_override, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'card_pay_lang_override', must be one of '%s'",
                    $card_pay_lang_override,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['card_pay_lang_override'] = $card_pay_lang_override;

        return $this;
    }

    /**
     * Gets is_pre_authorization
     *
     * @return bool|null
     */
    public function getIsPreAuthorization()
    {
        return $this->container['is_pre_authorization'];
    }

    /**
     * Sets is_pre_authorization
     *
     * @param bool|null $is_pre_authorization If true - pre-authorization transaction
     *
     * @return self
     */
    public function setIsPreAuthorization($is_pre_authorization)
    {
        if (is_null($is_pre_authorization)) {
            throw new \InvalidArgumentException('non-nullable is_pre_authorization cannot be null');
        }
        $this->container['is_pre_authorization'] = $is_pre_authorization;

        return $this;
    }

    /**
     * Gets card_holder
     *
     * @return string
     */
    public function getCardHolder()
    {
        return $this->container['card_holder'];
    }

    /**
     * Sets card_holder
     *
     * @param string $card_holder The card holder name. In case of Direct API either cardHolder or email is mandatory
     *
     * @return self
     */
    public function setCardHolder($card_holder)
    {
        if (is_null($card_holder)) {
            throw new \InvalidArgumentException('non-nullable card_holder cannot be null');
        }
        if ((mb_strlen($card_holder) > 45)) {
            throw new \InvalidArgumentException('invalid length for $card_holder when calling CardDetail., must be smaller than or equal to 45.');
        }
        if ((mb_strlen($card_holder) < 2)) {
            throw new \InvalidArgumentException('invalid length for $card_holder when calling CardDetail., must be bigger than or equal to 2.');
        }
        if ((!preg_match("/^[ 0-9a-zA-Z.@_-]{2,45}$/", ObjectSerializer::toString($card_holder)))) {
            throw new \InvalidArgumentException("invalid value for \$card_holder when calling CardDetail., must conform to the pattern /^[ 0-9a-zA-Z.@_-]{2,45}$/.");
        }

        $this->container['card_holder'] = $card_holder;

        return $this;
    }

    /**
     * Gets billing_address
     *
     * @return \Tatrapayplus\TatrapayplusApiClient\Model\Address|null
     */
    public function getBillingAddress()
    {
        return $this->container['billing_address'];
    }

    /**
     * Sets billing_address
     *
     * @param \Tatrapayplus\TatrapayplusApiClient\Model\Address|null $billing_address billing_address
     *
     * @return self
     */
    public function setBillingAddress($billing_address)
    {
        if (is_null($billing_address)) {
            throw new \InvalidArgumentException('non-nullable billing_address cannot be null');
        }
        $this->container['billing_address'] = $billing_address;

        return $this;
    }

    /**
     * Gets shipping_address
     *
     * @return \Tatrapayplus\TatrapayplusApiClient\Model\Address|null
     */
    public function getShippingAddress()
    {
        return $this->container['shipping_address'];
    }

    /**
     * Sets shipping_address
     *
     * @param \Tatrapayplus\TatrapayplusApiClient\Model\Address|null $shipping_address shipping_address
     *
     * @return self
     */
    public function setShippingAddress($shipping_address)
    {
        if (is_null($shipping_address)) {
            throw new \InvalidArgumentException('non-nullable shipping_address cannot be null');
        }
        $this->container['shipping_address'] = $shipping_address;

        return $this;
    }

    /**
     * Gets comfort_pay
     *
     * @return \Tatrapayplus\TatrapayplusApiClient\Model\CardIdentifierOrRegister|null
     */
    public function getComfortPay()
    {
        return $this->container['comfort_pay'];
    }

    /**
     * Sets comfort_pay
     *
     * @param \Tatrapayplus\TatrapayplusApiClient\Model\CardIdentifierOrRegister|null $comfort_pay comfort_pay
     *
     * @return self
     */
    public function setComfortPay($comfort_pay)
    {
        if (is_null($comfort_pay)) {
            throw new \InvalidArgumentException('non-nullable comfort_pay cannot be null');
        }
        $this->container['comfort_pay'] = $comfort_pay;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


