<?php
/**
 * CardPayStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tatrapayplus\TatrapayplusApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TatraPayPlus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1_2024-05-27v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tatrapayplus\TatrapayplusApiClient\Model;
use \Tatrapayplus\TatrapayplusApiClient\ObjectSerializer;

/**
 * CardPayStatus Class Doc Comment
 *
 * @category Class
 * @description **CardPay status**  | Enum      | description | | ---------------- | ------------| | INIT              | initialized transaction     | | OK              | processed successfully transaction     | | FAIL              | failed transaction | | PA              | pre-authorization | | CPA              | completed pre-authorization | | SPA               | canceled preauthorization | | XPA               | expired pre-authorization | | CB               | returned payment | | AUTH_REQUIRED               | 3D secure authorization required | | AUTH_EXPIRED               | authorization expired | | AUTH_CANCELED               | authorization canceled |
 * @package  Tatrapayplus\TatrapayplusApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CardPayStatus
{
    /**
     * Possible values of this enum
     */
    public const INIT = 'INIT';

    public const OK = 'OK';

    public const FAIL = 'FAIL';

    public const PA = 'PA';

    public const CPA = 'CPA';

    public const SPA = 'SPA';

    public const XPA = 'XPA';

    public const CB = 'CB';

    public const AUTH_REQUIRED = 'AUTH_REQUIRED';

    public const AUTH_EXPIRED = 'AUTH_EXPIRED';

    public const AUTH_CANCELED = 'AUTH_CANCELED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INIT,
            self::OK,
            self::FAIL,
            self::PA,
            self::CPA,
            self::SPA,
            self::XPA,
            self::CB,
            self::AUTH_REQUIRED,
            self::AUTH_EXPIRED,
            self::AUTH_CANCELED
        ];
    }
}


