<?php
/**
 * PayLaterStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Tatrapayplus\TatrapayplusApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TatraPayPlus API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1_2024-05-27v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tatrapayplus\TatrapayplusApiClient\Model;
use \Tatrapayplus\TatrapayplusApiClient\ObjectSerializer;

/**
 * PayLaterStatus Class Doc Comment
 *
 * @category Class
 * @description Finance application status
 * @package  Tatrapayplus\TatrapayplusApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PayLaterStatus
{
    /**
     * Possible values of this enum
     */
    public const _NEW = 'NEW';

    public const CUSTOMER_CREATION_IN_PROGRESS = 'CUSTOMER_CREATION_IN_PROGRESS';

    public const LOAN_APPLICATION_IN_PROGRESS = 'LOAN_APPLICATION_IN_PROGRESS';

    public const LOAN_APPLICATION_FINISHED = 'LOAN_APPLICATION_FINISHED';

    public const LOAN_DISBURSED = 'LOAN_DISBURSED';

    public const CANCELED = 'CANCELED';

    public const EXPIRED = 'EXPIRED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::CUSTOMER_CREATION_IN_PROGRESS,
            self::LOAN_APPLICATION_IN_PROGRESS,
            self::LOAN_APPLICATION_FINISHED,
            self::LOAN_DISBURSED,
            self::CANCELED,
            self::EXPIRED
        ];
    }
}


